name = "PowerModelsInterface"
uuid = "7a4b9400-1441-4f08-9626-3f96e0a9a29b"
authors = ["Jose Daniel Lara <jdlara@berkeley.edu>", "Clayton Barrows"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"

[compat]
PowerModels = "~0.18"
PowerSystems = "^1.12.0"
